= Geomatys BOM

Defines a Bill Of Materials, to centralize third-party dependency declarations in a single document.

== Principle

Rely on https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-dependencies/build.gradle[Spring Boot dependencies BOM] to provide coherent versions of most third-party tools used in our products and projects, like :

 * Jackson
 * PostgreSQL JDBC driver
 * Spring framework
 * Apache commons
 * Many more...

Some addendums are done to fit our specific needs for our products and projects.

== Usage

There are two possible ways to use this BOM:

* Either for dependency management only, in which case you can import it in your project in your *dependencyManagement*:
+
[source, xml]
----
<project>
    ...
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.geomatys</groupId>
                <artifactId>geomatys-bom</artifactId>
                <version>2022.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
----
* Or for both dependency management and plugin version management. In this case, you have to set this BOM as your project parent:
+
[source, xml]
----
<project>
    <parent>
        <groupId>com.geomatys</groupId>
        <artifactId>geomatys-bom</artifactId>
        <version>2022.1</version>
    </parent>
    ...
</project>
----

== Releases

=== Versions

This BOM uses a calendar versioning in the form YYYY.X where :

. YYYY is the current year of era, fully expressed.
. X is a release increment number in the year.

